source 'https://rubygems.org'

gem 'berkshelf'
gem 'chef-rewind'
gem 'chef-sugar'

group :test do
  gem 'chef', '~> 11.10.2'
  gem 'rspec'
  gem 'chefspec'
  gem 'guard'
  gem 'guard-rspec'
end

group :integration do
  gem 'test-kitchen'
  gem 'kitchen-vagrant'
end
